#-- base --#
set -g default-terminal "screen-256color"
setw -g xterm-keys on
set -s escape-time 5
set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
setw -g automatic-rename on
setw -g aggressive-resize on
set -g extended-keys on
set -g extended-keys-format csi-u
set -g mouse on

# status bar
set -g status on
set -g status-interval 5
set -g status-left '[#S] '
set -g status-right '%Y-%m-%d %H:%M'
set -g status-left-length 20
set -g status-right-length 40
setw -g window-status-current-format '#I:#W#F'
setw -g window-status-format '#I:#W#F'

#-- bindkeys --#
bind-key R source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# navigate panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# key bindings for horizontal and vertical panes
unbind %
bind | split-window -h      # |
unbind '"'
bind - split-window -v      # -

# swap panes
bind < swap-pane -U
bind > swap-pane -D
bind q kill-pane
bind ^e last-pane

# pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# window navi
bind-key -n F3 previous-window
bind-key -n F4 next-window


# Terminal settings
#set-window-option -g utf8 on
#Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Copy/Hist mode
setw -g mode-keys vi
bind p paste-buffer

bind-key X set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"
